# Generated by Django 5.0.7 on 2024-07-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(default='', max_length=11, verbose_name='User Phone Number'),
        ),
    ]
